name: Container Retention Policy

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "5 * * * *" # every hour

jobs:
  clean:
    runs-on: ubuntu-latest
    name: delete old sha-tag docker images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: cusk-io
          token: ${{ secrets.GHT_PAT_CONTAINER_RETENTION_POLICY }}
          image-names: "presidio-analyzer otherexample"
          image-tags: "sha-* otherprefix*"
          cut-off: 12h
          dry-run: false
